### ISSUE TITLE
Issue with adding Test cases to test run using add button in test run.

### ISSUE THREAD

**Issue by Rahulgowdagn1999** [Nitrate/Nitrate#1171]
1) Create a test run , after creating the test run there is on Add option in cases.
2) If I click on add it will be redirected to add  test cases.
3) While adding the test cases getting 500 Service Error.

**Comment by jrr-xena** [comment]
I am new to Nitrate, and have experienced this same issue. Details about the error and my environment:

Environment:


Request Method: POST
Request URL: http://192.168.56.101:8001/run/3/assigncase/

Django Version: 3.2.25
Python Version: 3.10.8
Installed Applications:
('django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_comments',
 'kobo.django.xmlrpc',
 'tinymce',
 'tcms.auth.apps.AppConfig',
 'tcms.comments.apps.AppConfig',
 'tcms.linkreference',
 'tcms.logs',
 'tcms.issuetracker',
 'tcms.management',
 'tcms.profiles',
 'tcms.testcases',
 'tcms.testplans',
 'tcms.testruns',
 'tcms.xmlrpc.apps.AppConfig',
 'tcms.report',
 'tcms.core.apps.AppConfig',
 'debug_toolbar')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware')



Traceback (most recent call last):
  File "/project/venv/lib64/python3.10/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/project/venv/lib64/python3.10/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/project/venv/lib64/python3.10/site-packages/kombu/utils/json.py", line 63, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
  File "/usr/lib64/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/project/venv/lib64/python3.10/site-packages/kombu/utils/json.py", line 47, in default
    return super().default(o)
  File "/usr/lib64/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

During handling of the above exception (Object of type timedelta is not JSON serializable), another exception occurred:
  File "/project/venv/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/project/venv/lib64/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/project/venv/lib64/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/project/venv/lib64/python3.10/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/project/venv/lib64/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/project/venv/lib64/python3.10/site-packages/tcms/testruns/views.py", line 1191, in post
    tr.save(update_fields=["estimated_time"])
  File "/project/venv/lib64/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/project/venv/lib64/python3.10/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/project/venv/lib64/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/project/venv/lib64/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/project/venv/lib64/python3.10/site-packages/tcms/testruns/signals.py", line 28, in mail_notify_on_test_run_creation_or_update
    mail_notify(run, template, subject, context)
  File "/project/venv/lib64/python3.10/site-packages/tcms/core/mailto.py", line 35, in mail_notify
    mailto(template, subject, recipients, context, cc=cc)
  File "/project/venv/lib64/python3.10/site-packages/tcms/core/task.py", line 48, in __call__
    return self.target.delay(*args, **kwargs)
  File "/project/venv/lib64/python3.10/site-packages/celery/app/task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "/project/venv/lib64/python3.10/site-packages/celery/app/task.py", line 575, in apply_async
    return app.send_task(
  File "/project/venv/lib64/python3.10/site-packages/celery/app/base.py", line 788, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/project/venv/lib64/python3.10/site-packages/celery/app/amqp.py", line 510, in send_task_message
    ret = producer.publish(
  File "/project/venv/lib64/python3.10/site-packages/kombu/messaging.py", line 175, in publish
    body, content_type, content_encoding = self._prepare(
  File "/project/venv/lib64/python3.10/site-packages/kombu/messaging.py", line 268, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/project/venv/lib64/python3.10/site-packages/kombu/serialization.py", line 219, in dumps
    with _reraise_errors(EncodeError):
  File "/usr/lib64/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/project/venv/lib64/python3.10/site-packages/kombu/serialization.py", line 45, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/project/venv/lib64/python3.10/site-packages/kombu/exceptions.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/project/venv/lib64/python3.10/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/project/venv/lib64/python3.10/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
  File "/project/venv/lib64/python3.10/site-packages/kombu/utils/json.py", line 63, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
  File "/usr/lib64/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/project/venv/lib64/python3.10/site-packages/kombu/utils/json.py", line 47, in default
    return super().default(o)
  File "/usr/lib64/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: EncodeError at /run/3/assigncase/
Exception Value: Object of type timedelta is not JSON serializable
