### ISSUE TITLE
"Update versions failed" when go to Planning > New Plan

### ISSUE THREAD

**Issue by dbo2qa** [Nitrate/Nitrate#287]
Description of problem:
When I go to Planning > New Plan, a message "Update versions failed" appears

Steps to Reproduce:
1. Login
2. Go to Planning > New Plan

Actual results:
A message "Update versions failed" appears

Expected results:
The message should not appear

Traceback:
`Internal Server Error: /management/getinfo/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/fedora/Nitrate/tcms/core/ajax.py", line 165, in info
    obj(),
  File "/home/fedora/Nitrate/tcms/core/ajax.py", line 149, in versions
    return Version.objects.filter(product__id=self.product_id)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/lib64/python2.7/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'null'
[04/Mar/2018 16:22:59] "GET /management/getinfo/?info_type=versions&product_id=null HTTP/1.1" 500 22503
`

**Comment by tkdchen** [comment]
This was fixed recently. Please pull latest code and run again.

**Comment by tkdchen** [comment]
This seems still happen when running on a fresh database. I'll look into this issue.
