### ISSUE TITLE
Traceback error while typing characters to add a tag

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#387]
```
Internal Server Error: /management/getinfo/
Traceback (most recent call last):
  File "/code/Nitrate/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/code/Nitrate/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/code/Nitrate/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/Nitrate/.env/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/code/Nitrate/src/tcms/core/ajax.py", line 156, in info
    for o in obj():
  File "/code/Nitrate/src/tcms/core/ajax.py", line 131, in tags
    '|'.join(["models.Q(name__startswith = '%s')" % item for item in seq])
  File "<string>", line 1, in <module>
NameError: name 'models' is not defined
```

**Comment by tkdchen** [comment]
But, this does not block adding a tag.
