### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by tkdchen** [Nitrate/Nitrate#72]
@jianchen2580 
@BrickXu 

Hi guys, do you still remember how to run tests? I run the tests in either

```
make test
```

or

```
./manage.py test --settings=tcms.settings.test
```

Lots of errors and failures. Looks something wrong of the way I run the tests. Need your help. Thanks.

**Comment by tkdchen** [comment]
Part of the output is

```
======================================================================
FAIL: test_plan_cases (tcms.testplans.tests.PlanTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cqi/projects/Nitrate/code/Nitrate/tcms/testplans/tests.py", line 48, in test_plan_cases
    assert response.status_code in self.status_codes
AssertionError

======================================================================
FAIL: test_plan_delcase (tcms.testplans.tests.PlanTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cqi/projects/Nitrate/code/Nitrate/tcms/testplans/tests.py", line 72, in test_plan_delcase
    assert response.status_code in self.status_codes
AssertionError

======================================================================
FAIL: test_plan_details (tcms.testplans.tests.PlanTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cqi/projects/Nitrate/code/Nitrate/tcms/testplans/tests.py", line 40, in test_plan_details
    assert response.status_code in self.status_codes
AssertionError

======================================================================
FAIL: test_plan_export (tcms.testplans.tests.PlanTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cqi/projects/Nitrate/code/Nitrate/tcms/testplans/tests.py", line 104, in test_plan_export
    assert response.status_code in self.status_codes
AssertionError

======================================================================
FAIL: test_plan_history (tcms.testplans.tests.PlanTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cqi/projects/Nitrate/code/Nitrate/tcms/testplans/tests.py", line 120, in test_plan_history
    assert response.status_code in self.status_codes
AssertionError
```

**Comment by tkdchen** [comment]
We need to rescue the tests.
