### ISSUE TITLE
new deployment and get error info

### ISSUE THREAD

**Issue by linglingfa1212** [Nitrate/Nitrate#957]
i'm trying to deploy a new Nitrate, got the below error info.How to fix it?

[root@localhost ~]# podman run -p 80:80 -t quay.io/nitrate/nitrate:4.11
Traceback (most recent call last):
  File "/bootstrap/init.py", line 14, in <module>
    django.setup()
  File "/usr/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/tcms/__init__.py", line 5, in <module>
    if settings.ASYNC_TASK == 'CELERY':
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/tcms/settings/product.py", line 27, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Environment variable NITRATE_SECRET_KEY must be set to provide a unique secret key to the Django's SECRET_KEY
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.88.0.3. Set the 'ServerName' directive globally to suppress this message

![error](https://user-images.githubusercontent.com/38340208/124740365-51a25100-df4d-11eb-91d4-5ecb2af9e02f.png)

**Comment by tkdchen** [comment]
@linglingfa1212 

For security reason, Django requires every deployment has its own SECRET_KEY. If you would like to deploy Nitrate in your own way with the images, please ensure to set the SECRET_KEY.

If you are just trying to run locally, you can podman-compose or docker-compose to up the containers. Please note that, the container-compose.yml file also has some information or hint for deployment.

**Comment by GatewayJ** [comment]
不明白nitrate_custom_conf模块要写什么内容？

**Comment by johnzhangchina** [comment]
我也遇到了同样的问题，并且根据问题的回答产生了以下疑惑：
1. 如何设置SECRET_KEY？
2. 如果我只在local运行，docker run和docker-compose貌似没有什么区别

**Comment by tkdchen** [comment]
> 不明白nitrate_custom_conf模块要写什么内容？

如果想覆盖 `tcms/settings/product.py` 里的配置，可以写在这个文件里。 `contrib/compose/web_custom_conf.py` 是个例子。

这个文件是可选的。如果你在容器环境中部署，也可以准备好一份调整好的 product.py ，然后通过容器环境的特定机制注入到Nitrate的容器里。例如，如果是用 Kubernetes 或者 OpenShift，可以用 configmap 注入。

> 如何设置SECRET_KEY？

这是个随机字符串，可以参考 https://docs.djangoproject.com/en/3.2/ref/settings/#secret-key

> 如果我只在local运行，docker run和docker-compose貌似没有什么区别

container-compose.yml 还是包含了很多配置的。直接用 docker run 在本地起容器也不是不行，只是很多东西都得你自己写，比较麻烦。
